### ISSUE TITLE
Textarea or Markdown

### ISSUE THREAD

**Issue by wm-simon** [FrameworkDesign/pinpoint-image#1]
Hey, thanks for your addon. I would like to use it, but I need for the pointers a textarea or markdown field.  Do you see a chance to add this or add a switch, where the fieldtype could be changed?

**Comment by paulweareframework** [comment]
Hello @wm-simon, I must humbly apologise about the delay in replying.
I was on holiday but back now.
And none of my team thought to check but will make sure that does not happen again.

So you have brought up a feature we wish to bring in the very next update.
We discussed internally and wish to ask you for your opinion:
- where could you see the field type (textarea or markdown) option living?
- - A setting on the fieldtype in blueprint?
- - A global settings for pinpoint-image to choose?
- - On the actual page, as in for each point you create an extra button to choose fieldtype in a popup?

I think the easiest to implement would be having it as an extra option on the blueprint fieldtype but we wish for any feedback to aid any user.

thank you and look forward to your response

**Comment by wm-simon** [comment]
Hey @paulweareframework, thanks for your feedback. I was on holiday too, so it's all fine.
I think the solution inside the blueprint settings would be the best, too. Perhaps you can add a modal for the field content, the space fot text is not that big right now. I would like to use for myself and explain website screenshots with little info points.

![image](https://user-images.githubusercontent.com/3351449/179097027-4e33d796-5647-4881-bf93-9146e9bb0468.png)

**Comment by paulweareframework** [comment]
@wm-simon ok fantastic, we are in the process of creating this update and will let you know as soon as it is ready :)

**Comment by paulweareframework** [comment]
@wm-simon I've just pushed up changes:

sorry for the extra day its taken!
I've just tagged v0.0.7 and this now has:
- change the order from the pinpoints (via drag & drop)
- move the pinpoints position (via drag & drop)
- Modal for field content
- multiple fields in modal content 
- - markdown, textarea & text so far
- updated template tag with example of how to output the new fields

If you could give it a try and let me know if its good for you :)

**Comment by wm-simon** [comment]
Hey, thank you! Composer is not updating. The new version is not listed on the marketplace:
https://statamic.com/addons/weareframework/pinpoint-image/release-notes

**Comment by paulweareframework** [comment]
@wm-simon no idea why it took so long to show up in the statamic add on store but it finally just changed to 0.0.7
https://statamic.com/addons/weareframework/pinpoint-image

**Comment by paulweareframework** [comment]
Am I ok to close this now?
