### ISSUE TITLE
Statamic v4 support

### ISSUE THREAD

**Issue by tobimori** [FrameworkDesign/pinpoint-image#10]
<img width="865" alt="CleanShot 2023-05-11 at 23 58 20@2x" src="https://github.com/FrameworkDesign/pinpoint-image/assets/29142128/ae4a7b18-fcad-47a9-acf7-058d502112f0">
Current layout in Statamic v4 is broken.
Drag and drop is also not working.

**Comment by paulweareframework** [comment]
thank you for alerting me to this!
I will get an update out as soon as I can and provide an update here when I do so

**Comment by paulweareframework** [comment]
Sorry about the delay, @tobimori could you please update to latest version (0.0.11)
This should resolve statamic 4 issue you are experiencing
