### ISSUE TITLE
Bug inside replicator field

### ISSUE THREAD

**Issue by wm-simon** [FrameworkDesign/pinpoint-image#4]
I have the pinpoint field inside a replicator to show multiple images on a site. Something seems to work wrong, because already selected images are moved to the newest replicator field and deleted from the older once. When you duplicate a replicator field and select an image to for the pinpoint field, other images are deleted or moved as well. I can not explain, what exactly happens here, but it seems to be buggy.

**Comment by paulweareframework** [comment]
hello @wm-simon I will look into getting this resolved. Humble apologies if this has held you up so far.

**Comment by paulweareframework** [comment]
I've deployed a fix to this on v0.0.10

Please update and I believe this should resolve this issue
