### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by wm-simon** [FrameworkDesign/pinpoint-image#5]
It would be cool, if it would be possible to:
- change the order from the pinpoints (via drag & drop)
- move the pinpoints position (via drag & drop)

**Comment by paulweareframework** [comment]
This is going to be added to the current update which will roll in for the update https://github.com/FrameworkDesign/pinpoint-image/issues/1

**Comment by paulweareframework** [comment]
@wm-simon I've just pushed up changes:

sorry for the extra day its taken!
I've just tagged v0.0.7 and this now has:
- change the order from the pinpoints (via drag & drop)
- move the pinpoints position (via drag & drop)
- Modal for field content
- multiple fields in modal content
- - markdown, textarea & text so far
- updated template tag with example of how to output the new fields

If you could give it a try and let me know if its good for you :)

**Comment by paulweareframework** [comment]
Am I ok to close this now?
