### ISSUE TITLE
Bug for GraphQL query

### ISSUE THREAD

**Issue by bogdanarizancu** [FrameworkDesign/pinpoint-image#6]
We are using Statamic in headless mode and when we query for the field via GraphQL, we get the following server error:

```bash
 "Expected a value of type \"String\" but received: {\"image\":\"assets::llamas.jpg\",\"annotations\":[{\"x\":19,\"y\":9,\"data\":{\"heading\":\"Test heading 1\",\"fields\":[]}},{\"x\":62,\"y\":34,\"data\":{\"heading\":\"test heading 2\",\"fields\":[]}}]}",
```

<img width="1636" alt="image" src="https://user-images.githubusercontent.com/11241985/185935187-58ab862e-95e9-470a-b82e-ab06ad246fdb.png">

**Comment by paulweareframework** [comment]
Humble apologies you are experiencing this issue @bogdanarizancu 
We will jump onto resolving this issue and update you accordingly when a fix is deployed

**Comment by bogdanarizancu** [comment]
@paulweareframework — any idea when this would be possible?

**Comment by paulweareframework** [comment]
> @paulweareframework — any idea when this would be possible?

Should be deployed and tagged end of today or tomorrow. 
Sorry about the delay. first week was learning how to do it! (graphQL in statamic addons)

But now outputting the fields and hopefully in a format you agree with/find helpful.

**Comment by paulweareframework** [comment]
@bogdanarizancu 0.0.9 version is pushed up. Could you please take a look and hopefully this is good for you?

**Comment by bogdanarizancu** [comment]
@paulweareframework — thank you for the quick fix, I am now not getting any server error anymore. However I can't seem to find any fields to query for, please check a screenshot. `Set_Components_HotspotImage` is not selectable as if there are no fields available to query for, am I missing something here?
<img width="1537" alt="image" src="https://user-images.githubusercontent.com/11241985/189923504-a09654bc-dc06-4b56-a4d1-0a71e634854d.png">

**Comment by paulweareframework** [comment]
@bogdanarizancu Can you not click the component Set_Components_HotspotImage ?

It should then reveal three fields you can pull with it, I've attached example screenshot pulling in
![Screenshot 2022-09-14 at 11 11 56](https://user-images.githubusercontent.com/46562148/190127229-33f4da18-9ebc-434e-8eba-341dc0f05071.png)

**Comment by sun** [comment]
Sorry for the late reply - Bogdan didn't have time to look into this. One of our other developers will check the query and whether the data can be used now. Thanks for implementing a fix so promptly!

**Comment by paulweareframework** [comment]
> Sorry for the late reply - Bogdan didn't have time to look into this. One of our other developers will check the query and whether the data can be used now. Thanks for implementing a fix so promptly!

thank you and hope its all good or you now :)
