### ISSUE TITLE
Issues when using alongside Bard

### ISSUE THREAD

**Issue by duncanmcclean** [FrameworkDesign/pinpoint-image#8]
We're having an issue with the fieldtype when using it inside Bard sets...

## Reproduction steps

1. Create a Bard field, with a set. Add the pinpoint fieldtype as a field in the set
2. Go to edit in the Bard field. Add a set, select an image & add some pins
3. Add another set - see the image & pins copied across from the first

Video demonstration: https://www.loom.com/share/b81e539b5a9c40d482b80871169d6736

I've pushed up [a demo repo](https://github.com/duncanmcclean/pinpoint-bard-issue) to make it nice and easy to replicate - edit the Home page.

## Why..

I've done a little bit of digging around since we're still using our modified version of the addon. It looks like for whatever reason, after adding the initial image, the data is set as the 'default value' for future sets.

You can see this if you open the `BardFieldtype` in Vue Dev Tools, then find the `meta.defaults` part, then the set handle, then the field handle, you can see that a default value has been set:

![image](https://user-images.githubusercontent.com/19637309/193055680-fde78429-1908-4f9a-bf26-37d5e92d45b0.png)

We're planning to deliver this project early next week so trying to wrap it up and get it fixed this afternoon. If I find the fix, I'll attempt to PR it.

**Comment by paulweareframework** [comment]
I've deployed a fix to this on v0.0.10

Please update and I believe this should resolve this issue

**Comment by duncanmcclean** [comment]
Thanks - I can confirm it's now fixed! 🚀
